### ISSUE TITLE
Crash on Server Connection

### ISSUE THREAD

**Issue by GlacierPark19** [team-abnormals/abnormals-core#101]
Hello,

While playing the Modpack Valhelsia 3, I discovered this error:

[10May2021 14:04:51.730] [Render thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to reference chain thatch->thatch in abnormals_core:block/thatch/thatch_stairs_inner

My latest.log and debug.logs are attached
[latest.log](https://github.com/team-abnormals/abnormals-core/files/6462551/latest.log)

[debug.log](https://github.com/team-abnormals/abnormals-core/files/6462548/debug.log)

**Comment by SmellyModder** [comment]
This is an issue caused by the Connected Textures Mod (CTM).
Relates to https://github.com/Chisel-Team/ConnectedTexturesMod/issues/149 and https://github.com/team-abnormals/abnormals-core/issues/69
