### ISSUE TITLE
Not all signs or boats work propperly

### ISSUE THREAD

**Issue by Eriador26** [team-abnormals/abnormals-core#107]
Hello I have run into some problems with the signs and just the signs it seems.

The following tree type planks will give the following signs which are wrong ofcourse.

Dead -> Spruce
Palm -> Acacia
Fir -> Oak
Redwood -> Acacia
Jacaranda -> Jungle
Umbran -> Dark Oak
Magic -> Birch

and when making boats the proper boat is shown but than gets flipped into a vanilla typ wood boat when placed.

The other 4 give their sign just fine, but have problems with the boats as well.
It seems like something is telling the work bench to prefer the vanilla sign over the according quark o plenty sign.
Tested on the server and in single player, both have the same result. Also with less mods active. same issue occurs.

Any idea how I can fix tthis?

**Comment by bageldotjpg** [comment]
This has nothing to do with Abnormals Core. Biomes O' Plenty doesn't even use Abnormals Core - they intentionally implemented these recipes because they don't have actual signs for thsoe wood types
