### ISSUE TITLE
Crash with OuterEnd

### ISSUE THREAD

**Issue by TheFoxHunt** [team-abnormals/abnormals-core#109]
[crash-2021-06-14_13.00.36-fml.txt](https://github.com/team-abnormals/abnormals-core/files/6645737/crash-2021-06-14_13.00.36-fml.txt)

**Comment by Brittank88** [comment]
Can confirm [the crash](https://gist.github.com/Brittank88/498936f5c14e36cbde7079a2fcd61a56).

**Comment by Brittank88** [comment]
This downgrade prevents the crash:
![image](https://user-images.githubusercontent.com/24266948/121891713-28800d80-cd5f-11eb-951d-d498892a4c02.png)

**Comment by TheFoxHunt** [comment]
Noted with thanks!

**Comment by Shap54** [comment]
Can also confirm.
When I loaded a previous version of abnormals core however I lost the ability to craft crafting tables and chests with basic planks.
I don't know if it is specifically abnormals core that is causing this but I didn't have the problem last week when I last played, could have been one of my other updates

**Comment by SmellyModder** [comment]
Related to #112
