### ISSUE TITLE
Crash with....a bunch of mods. (abnormals_core-1.16.5-3.2.0)

### ISSUE THREAD

**Issue by PurpleHel** [team-abnormals/abnormals-core#111]
Definitely abnormals core cos I had only updated a couple mods, so I just stepped back through them.
crash log https://pastebin.com/3xsE6L7H
latest.log https://pastebin.com/x1ZigpLa
debug.log https://pastebin.com/8xMW0q4J
just list of mods https://pastebin.com/3mcjrbck

**Comment by SmellyModder** [comment]
Related to #112
