### ISSUE TITLE
Crash Error

### ISSUE THREAD

**Issue by SwagStev3** [team-abnormals/abnormals-core#113]
[crash-2021-06-16_18.27.59-fml.txt](https://github.com/team-abnormals/abnormals-core/files/6661511/crash-2021-06-16_18.27.59-fml.txt)
Whenever I load up Minecraft (I am using an absurd amount of mods) I get this error message, I looked at it and it appears to have something to do with Abnormals Core. Any help? 
Thanks

**Comment by SmellyModder** [comment]
Related to #112
