### ISSUE TITLE
[1.16.5] Broken thatch model for inner_top and outer_top

### ISSUE THREAD

**Issue by vectorwing** [team-abnormals/abnormals-core#115]
### Description
As of the latest version of Abnormals Core, the template Thatch models for `thatch_stairs_inner_top` and `thatch_stairs_outer_top` have broken extrudes, flipped upside down and floating off the main block.

Inspecting a bit, it seems those two models are not manually flipped into the model itself, like `thatch_stairs_top` and `thatch_slab_top` are, instead being rotated within the blockstates file. I was able to partially correct the problem by editing the models and rotating the extrude UVs by 180 degrees. However, when rotated by the blockstates file, the extrudes also had a minor floating point misplacement to them (see below).

### Screenshots
![image](https://user-images.githubusercontent.com/5566692/122687495-1eda2800-d1ed-11eb-9921-0b5fd7411284.png)
![image](https://user-images.githubusercontent.com/5566692/122687523-3addc980-d1ed-11eb-8b82-ae52875be629.png)

A. `thatch_stairs_top` (extrudes are flush)
B. `thatch_stairs_outer_top` (extrudes slightly off)
![image](https://user-images.githubusercontent.com/5566692/122687542-5c3eb580-d1ed-11eb-9317-493a0ba04955.png)

### Mod List
Forge 36.1.32

abnormals_core-1.16.5-3.2.0
environmental-1.16.5-1.0.0
upgrade_aquatic-1.16.5-3.1.0

**Comment by SmellyModder** [comment]
I can't seem to get the extrudes to be rotated correctly and not be offset a bit without actually changing the default rotation of the models.
Changing the models to be rotated upside down by default (like `thatch_stairs_top`) would be the solution to this, but that would break existing blockstates using the current models.

**Comment by velocityraptor-real** [comment]
Logger constantly spamming:
[Render thread/WARN]: Unable to resolve texture due to reference chain thatch->thatch in abnormals_core:block/thatch/thatch_stairs_inner
[Render thread/WARN]: Unable to resolve texture due to reference chain extrudes->extrudes in abnormals_core:block/thatch/thatch_stairs_inner
And so on.
Clumps the log and makes it unreadable.
To my knowledge there is sadly no SASIT mod that can supress log messages, so please solve this for 1.16.5.
Example Log: (Deleted Modpack Startup log entries, so you don't need to scroll down to see the messages)
[2021-09-28-2.log](https://github.com/team-abnormals/abnormals-core/files/7245533/2021-09-28-2.log)

**Comment by SmellyModder** [comment]
> Logger constantly spamming: [Render thread/WARN]: Unable to resolve texture due to reference chain thatch->thatch in abnormals_core:block/thatch/thatch_stairs_inner [Render thread/WARN]: Unable to resolve texture due to reference chain extrudes->extrudes in abnormals_core:block/thatch/thatch_stairs_inner And so on. Clumps the log and makes it unreadable. To my knowledge there is sadly no SASIT mod that can supress log messages, so please solve this for 1.16.5. Example Log: (Deleted Modpack Startup log entries, so you don't need to scroll down to see the messages) [2021-09-28-2.log](https://github.com/team-abnormals/abnormals-core/files/7245533/2021-09-28-2.log)

The log spam here is not related to this issue nor even caused by Abnormals Core directly.
Reference to the cause of your issue: https://github.com/Chisel-Team/ConnectedTexturesMod/issues/149

**Comment by velocityraptor-real** [comment]
Thank you for your help.

**Comment by Diaboy01** [comment]
Unfortunately still not fixed :(
