### ISSUE TITLE
Crash with Create v0.3.1c

### ISSUE THREAD

**Issue by FrozenToothpaste** [team-abnormals/abnormals-core#116]
Just doesnt load at all

After Mojang screen I get:
Create (create) has failed to load correctly.

java.lang.ExceptionInInitializerError: null 

This was on Abnormals core v3.2.0. I reverted back to v3.1.1 and the game loaded

**Comment by Wedge1453** [comment]
same issue, either add Optifine, or downgrade Abnormal Core

**Comment by SmellyModder** [comment]
This is technically an issue on Create's side.
Forge added a PR to register new `WoodType`s and Create was not designed to handle it.
Create has fixed this issue in this commit: https://github.com/Creators-of-Create/Create/commit/785242d5b3a4b425ada6943d964ed98fe7440826
Also related to #112
