### ISSUE TITLE
Compatibility Issue: create

### ISSUE THREAD

**Issue by KsarZ** [team-abnormals/abnormals-core#117]
the latest version of abnormals core doesn't work with create mod. Here's log
[crash-2021-06-25_13.04.33-fml.txt](https://github.com/team-abnormals/abnormals-core/files/6715656/crash-2021-06-25_13.04.33-fml.txt)

**Comment by KsarZ** [comment]
#

**Comment by Diversion98** [comment]
why is this closed?
I have the same issue with the latest version, i had to downgrade it again.
