### ISSUE TITLE
Create mod cant work properly with latest Abnormals core 

### ISSUE THREAD

**Issue by xinyialabamaman** [team-abnormals/abnormals-core#125]
Server crash report:
Crash Report UUID: 031a2650-d17d-45ab-b1d7-825157eb72ed[19:12:12] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Create (create) has failed to load correctly
§7java.lang.ExceptionInInitializerError: null
]

**Comment by SmellyModder** [comment]
Related to https://github.com/Creators-of-Create/Create/issues/1799
