### ISSUE TITLE
Will it cause other mods to crash?

### ISSUE THREAD

**Issue by dajiuji** [team-abnormals/abnormals-core#127]
Hello, can this mod cause other mods to crash? In the 3.2.0 version, it will cause a lot of problems...so I have been using 3.1.1, but recently you are constantly updating to use Abnormals-core as the pre-mod, which makes me have to update this pre-mod. So I want to ask, is that problem solved? Because neither those mods nor your mods, I can't give up.

**Comment by SmellyModder** [comment]
Any mod can cause any mod to crash technically.
Abnormals Core recently went through some internal changes with signs that have been affecting some other mods.
Related to #112
