### ISSUE TITLE
Abmormals Team mods on 1.16.4

### ISSUE THREAD

**Issue by Wakatsu** [team-abnormals/abnormals-core#48]
Whenever I try to run any AT mods on 1.16.4 the game complains that the mods require minecraft 1.16.1, despite that my version is newer. No other mod behaves in such way. Please fix.

**Comment by SmellyModder** [comment]
It is complaining because our mods cannot run on versions higher than `1.16.1`.
If it said it requires `1.16.1+`, then there would be an issue.
Be patient and wait for us to update.
