### ISSUE TITLE
AC does not support Quark's new wooden posts

### ISSUE THREAD

**Issue by EltrutLikes** [team-abnormals/abnormals-core#49]
[In a recent update](https://github.com/Vazkii/Quark/commit/e65a456ce7c88044ad61aeff04177b630801cf5c), Quark added wooden posts, which are fence-like blocks that don't connect. AC as of now does not have compat code for them as it does for bookshelves, ladders, vertical slabs, and chests. I can submit a PR adding the code and JSON files in but I didn't know whether you wanted to check with Vazkii first because there will probably be significant code overlap (for obvious reasons).

**Comment by SmellyModder** [comment]
We currently don't add compatibility for wooden posts in our mods, which is why there is no support for them in AC.
It'll be added by us when it's needed. If you want to add compatibility for wooden posts, you'll just have to do it yourself for now.
