### ISSUE TITLE
Some Spawn Eggs aren't sorted in alphabetical order

### ISSUE THREAD

**Issue by WitheredWasabi** [team-abnormals/abnormals-core#54]
They are sorted in between vanilla spawn eggs but sometimes not in the right place, some spawn eggs such as neapolitan ones aren't even sorted with vanilla and modded spawn eggs

**Comment by SmellyModder** [comment]
I can confirm the alphabetical sorting working incorrectly sometimes, and I noticed it a bit ago myself.
Spawn eggs not being sorted at all doesn't sound like an AC issue. 
I haven't encountered spawns not being sorted at all. Elaborate more on what spawn eggs in specific are not being sorted at all.

**Comment by WitheredWasabi** [comment]
![sgdfdfgdgd](https://user-images.githubusercontent.com/38932715/102453942-085ed400-3ff2-11eb-8025-e8db062ca4b6.PNG)
![fdgdfgsgf](https://user-images.githubusercontent.com/38932715/102453950-08f76a80-3ff2-11eb-9635-555792617a69.PNG)
The Spawn Eggs are from s&r (Griefer, Executioner, Iceologer), NEx (Sporus), and Neapolitan (Plantain Spider, Monkey). Also Puff bugs from Endergetic aren't sorted either with the other Spawn Eggs either.

**Comment by SmellyModder** [comment]
Ah, I think I know the cause. The abnormal spawn eggs are sorting with modded spawn eggs that are also not sorted alphabetically, causing issues. I had a feeling removing the mixin would cause issues, and it did.
