### ISSUE TITLE
Mod loads client-sided class on the server-side causing crashes

### ISSUE THREAD

**Issue by papuSpartan** [team-abnormals/abnormals-core#59]
Server Debug Log: [https://gist.github.com/papuSpartan/942654c084683d96ebf74c25949951fb](url)
`Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.tileentity.ItemStackTileEntityRenderer`

thanks to the guys on the forge discord for finding this

**Comment by tobi1449** [comment]
I'm getting the same problem with abnormals-core 3.0.4 and minecolonies-0.13.543
https://pastebin.com/duJ9WWrP
