### ISSUE TITLE
Ticking World Crash When Loading A world or Creating A New World  [1.16.4/5]

### ISSUE THREAD

**Issue by Coraline77447** [team-abnormals/abnormals-core#67]
Hi, I'm experiencing a ticking world crash that's coming from Abnormals Core and another mod called Smoothboot with the mixin that they use. Here's the crash report and log;

Crash Report:  [crash-2021-01-16_05.58.44-server.txt](https://github.com/team-abnormals/abnormals-core/files/5824341/crash-2021-01-16_05.58.44-server.txt)

Log:   [latest.log](https://github.com/team-abnormals/abnormals-core/files/5824342/latest.log)

NOTE: Even tho I didn't see or couldn't see Abnormals Core in the Blame logs in my logs folder but in the crash report I did find Abnormals Core in there that its mixin along with Smooth Boot's mixin caused my new modded world to die without me ever spawning into the world...

UPDATE: I tried to create another world and it died again but without the mods i've though caused this and found out that OptiFine may be the one that's causing this since there's no 1.16.5 version for OptiFine yet. Im going to take out optifine and see if I can make a new world.

UPDATE 2: I tried to make another test world and it too died by the same ticking world crash but without abnormals-core, smoothboot, and optifine... I truly don't know what's causing this.... I seriously need help finding out which mod or mods that I have that are causing this mess...... I think that this issue relates to forge not the mods... The forge devs did somethin with the mixin and now I can't create a new world or load into an existing one since I get the java.lang.NoSuchMethodError....

**Comment by SmellyModder** [comment]
This isn't an Abnormals Core issue. Even though Abnormals Core mixins into `ServerWorld`, it doesn't modify anything tick related. This crash also happens inside `ServerChunkProvider`, and Abnormals Core doesn't do anything to that.
