### ISSUE TITLE
Abnormals Core Error causing Minecraft to freeze during load

### ISSUE THREAD

**Issue by Serifina** [team-abnormals/abnormals-core#69]
[latest.log](https://github.com/team-abnormals/abnormals-core/files/5872366/latest.log)

Attached is the log, as Minecraft is freezing and not generating a crash report. The primary information is that literally thousands and thousands of lines are being generated in the log like this:

[26Jan2021 01:13:44.306] [Render thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to reference chain thatch->thatch in abnormals_core:block/thatch/thatch_stairs_inner

starting at line 1094, and going down another _ten thousand lines_. I have no idea what's causing this.

**Comment by bageldotjpg** [comment]
Try reinstalling the mod

**Comment by Serifina** [comment]
Deleting and redownloading the mod, unfortunately, provided the same result.

**Comment by Serifina** [comment]
[latest.log](https://github.com/team-abnormals/abnormals-core/files/5874989/latest.log)
Disabled Storage Drawers, still doing it.

**Comment by Serifina** [comment]
Okay, so, I've tracked down which mod it's interacting with and causing it to freak out. Specifically, somehow it's an interaction with the Connected Textures Mod that's doing it. Why, I don't know, but it definitely shouldn't be doing that.

**Comment by Crokoking** [comment]
Specifically it happens if you have Abnormals-Core, Neapolitan and Connected Textures Mod all in the same pack. Neapolitan references the thatch base model from abnormals-core and my guess is that that causes Connected Textures Mod to scan the (by itself invalid) base model even though it is never used for a block on its own

**Comment by SmellyModder** [comment]
That'd be an issue on CTM's side. Open an issue over there.

**Comment by Hypsellis** [comment]
Farmers Delight suffers of the same issue.
https://github.com/vectorwing/FarmersDelight/issues/169

**Comment by bageldotjpg** [comment]
Yeah that's why it's likely a CTM issue

**Comment by bageldotjpg** [comment]
Has been marked as a CTM bug, follow it there: https://github.com/Chisel-Team/ConnectedTexturesMod/issues/149
