### ISSUE TITLE
Chests are invisible when waterlogged and player not targetting a block

### ISSUE THREAD

**Issue by LiskoSlayer63** [team-abnormals/abnormals-core#80]
Chests are also not rendered in water if GUI is disabled (by pressing F1). I  experienced this bug myself, but was able to fix it by adding the textures to an Atlas. I'd recommend to use chest atlas and then render with that like vanilla does.

**Abnormals Core:** 3.0.6
**Atmospheric:** 3.0.0

**With GUI and targetting:**
![2021-02-13_09 09 03](https://user-images.githubusercontent.com/10125529/107844366-5ec27600-6ddb-11eb-8823-3fb4220fa92e.png)

**Without GUI and targetting:**
![2021-02-13_09 09 06](https://user-images.githubusercontent.com/10125529/107844372-6c77fb80-6ddb-11eb-836d-43e1d93d50b5.png)

**With GUI but not targetting:**
![2021-02-13_09 09 18](https://user-images.githubusercontent.com/10125529/107844374-76016380-6ddb-11eb-91c5-3c518af2e824.png)

**Comment by SmellyModder** [comment]
I am unable to reproduce this.
Do you have any rendering mods like Optifine running?

**Comment by LiskoSlayer63** [comment]
@SmellyModder No, only Atmospheric and Abnormals Core. It can be reproduced simply by stepping back and pressing F1, *unless* graphics are set to Fabulous mode.

**Comment by SmellyModder** [comment]
I got it to happen a few times now. The conditions for it to occur are pretty finicky.
For now, use Fabulous graphics to get around this issue.
