### ISSUE TITLE
Abnormal core icompatibility

### ISSUE THREAD

**Issue by NoDreamsRemain** [team-abnormals/abnormals-core#83]
i'm trying to use the outher end mod, and when i load the core, the minecraft crashes and ofc i can't play. So im a bit confused and im trying to find out what's the issue

**Comment by bageldotjpg** [comment]
Can't help unless you send your latest.log

**Comment by NoDreamsRemain** [comment]
> Can't help unless you send your latest.log

wdym?

**Comment by NoDreamsRemain** [comment]
![image](https://user-images.githubusercontent.com/77308088/108159429-c7547000-70c5-11eb-9bfd-a6a2d6d0ce10.png)
it says "it happened a error and the game stoppe worrking. Exit code = 0"

**Comment by NoDreamsRemain** [comment]
it only happen when i use the core

**Comment by bageldotjpg** [comment]
Go to your minecraft logs folder and send the latest.log

**Comment by NoDreamsRemain** [comment]
this is my lastest log 
![image](https://user-images.githubusercontent.com/77308088/108159591-1b5f5480-70c6-11eb-8229-a7167eb18ede.png)

**Comment by NoDreamsRemain** [comment]
how may i open this

**Comment by NoDreamsRemain** [comment]
this is what the latest log says ‹       ÝUMoÓ@½WêÄ!—âÄŽŠ¥ á«j”"q¨ªj¼žÄK×»Öî8¤üzvCÚRˆC ô‚Göxæ½y;»ÏçI’Å½¬_Àù„tA¸´„E÷ýé›ñE¯õ\Z£+Òœ6\¾3Ž:%sí²n7DÙ9Ù¨2ŸQÏ"aªÎ ¦Ñì~Ê®åý4GÎI£ïg­‚ë`CL
Z+5	‹S¾IYUh¬è óa2uvwÎWjûmjÏˆYê4%ƒS3ò/+w9¡
¥Þ¢þŠ+%s‹ö:ƒãOGoÁëŠ %Qy#UqïoØ†wŠÖ"{S¿¦àá5ºi£Ô5(ƒ[ÀM(¤r¦±‚NPã,hÑÅ· iÒ2®I¿<©%KTò+ÑUg~;@zæçŽÑò·—úŸ™ùåJÒÅò/…ÛYgLn,¹.²B×Í•W.ªõìÙ2ð'É`¸ˆ“ýMðNÎô_¢/;ÄÉÆîQk²—52“}L"WJRÅ‰Âz…k(Éñ:ôÖós‹ü=§bmëÿÜ•ºòÃÈÍ‚Ö²¤[/P¯¥öÇ@
õ¨RG{ C8*“_ÒtJ‚åˆ³~¯•ÃøÝ.–nËž{kLQ?Š_ôö<ï`8Xø_0´“Ã±¯©ü¦Å\*É×pX’w[Oã;CU9pŽRa®hé˜\úPðôû«ôßÁÈ|ÑK+µÿïÇ/Íz­S?cS×~Ovw¾ëXØ$

**Comment by NoDreamsRemain** [comment]
![image](https://user-images.githubusercontent.com/77308088/108159699-51043d80-70c6-11eb-9263-807763c6c870.png)

**Comment by NoDreamsRemain** [comment]
or this one
![Uploading image.png…]()

**Comment by bageldotjpg** [comment]
No, it's a file named latest.log. Send that file.

**Comment by NoDreamsRemain** [comment]
[latest.log](https://github.com/team-abnormals/abnormals-core/files/5993403/latest.log)

**Comment by NoDreamsRemain** [comment]
i will be waiting for your response.

**Comment by NoDreamsRemain** [comment]
why taking so long?

**Comment by Iashar** [comment]
Well, what I'm seeing in that log references a Charm mixin. So something they're doing may be incompatible? Try dropping Charm and see if that helps. Then you'll know what dev to talk to.

**Comment by NoDreamsRemain** [comment]
> Well, what I'm seeing in that log references a Charm mixin. So something they're doing may be incompatible? Try dropping Charm and see if that helps. Then you'll know what dev to talk to.

yeah thank you

**Comment by NoDreamsRemain** [comment]
i actually wanted charm because it adds really cool thing y'know

**Comment by NoDreamsRemain** [comment]
i will close this because its solved. Thanks to everyone that helped me here!
