### ISSUE TITLE
Crash with latest OptiFine G7 1.16.5

### ISSUE THREAD

**Issue by Lawiel** [team-abnormals/abnormals-core#84]
Good time of the day,

Having a problem with Abnormals core, it has some kind of conflict (I'm not very good with coding) with latest OptiFine version,

I'm using latest version of Forge for 1.16.5 - 36.0.42,

OptiFine G6 works fine, but whenever I'm putting G7 in the mods folder Minecraft won't start and giving error at the launcher (without crash report), when I'm removing Abnormals Core and all related mods it works fine,

Here's the latest.log:
https://pastebin.com/Bz1jy1hq

And modlist:
https://pastebin.com/cwucqb1h

P.S. I've tried to remove all mods one by one and I'm sure that it's somehow related to that particular mod.

Already reported that to Optifine Github in a comment to the same issue:
https://github.com/sp614x/optifine/issues/5341

**Comment by bageldotjpg** [comment]
OptiFine crashes are not supported, as OptiFine is closed source so we can not possibly find the problem. I reccomend removing OptiFine if playing modded minecraft because you will continue to find more issues with more mods as you continue to play, almost all of which can not be fixed.
