### ISSUE TITLE
All the abnormals core mods cause massive lag for me

### ISSUE THREAD

**Issue by DarkShadow-999** [team-abnormals/abnormals-core#85]
I have a modpack of around 250 mods and my game runs at around 60 fps with it but if I even add a single abnormals core mod my fps drops to 1-3 fps. Using Blame mod I get the the message that dispenser behaviour overridden.

**Comment by bageldotjpg** [comment]
None of the mods are very FPS heavy, and dispenser behavior modifications / overrides would have nothing to do with that. Please provide a full log file

**Comment by DarkShadow-999** [comment]
[2021-02-23-2.log.gz](https://github.com/team-abnormals/abnormals-core/files/6033936/2021-02-23-2.log.gz)
this is the log file. I used extra boats and outer end mod in this and I was getting at most 10 fps with only 8 render distance.

**Comment by SmellyModder** [comment]
There is nothing in those logs to support our mods are causing bad FPS performance.

**Comment by DarkShadow-999** [comment]
Ok I will try your mods again and send the logs
