### ISSUE TITLE
Conflict with SystemZee's "Pillagers Plus"

### ISSUE THREAD

**Issue by waluigi12** [team-abnormals/abnormals-core#89]
I made an issues ticket on their mod, but I thought I should make one here too.
When loading up abnormals-core and pillagers plus, it says that "pillager trust" failed to load. 

[crash-2021-03-07_17.27.41-fml.txt](https://github.com/team-abnormals/abnormals-core/files/6097497/crash-2021-03-07_17.27.41-fml.txt)

**Comment by SmellyModder** [comment]
Does this still happen if you remove Abnormals Core?
This looks like an issue on their side.

**Comment by waluigi12** [comment]
It happens only with Abnormals Core in the game, I tried about 90 other mods I had, where it worked. 
Thanks for responding though!
