### ISSUE TITLE
Line of sight on baby animals' hitboxes are too high

### ISSUE THREAD

**Issue by BlueVsRed12** [team-abnormals/abnormals-core#91]
![image](https://user-images.githubusercontent.com/35225767/111689813-7e91f300-87fa-11eb-9e1f-e1382bcd8c60.png)

This also causes tall animals' baby variants (such as cows / sheep, not pigs / chickens) to suffocate when directly underneath a solid block. 

(the baby cow is taking damage here)
![image](https://user-images.githubusercontent.com/35225767/111690162-daf51280-87fa-11eb-853a-a2e27baa246f.png)

**Comment by bageldotjpg** [comment]
What's making you think this is Abnormals Core's fault? I can't reproduce this with just Abnormals Core or in a small modpack.

**Comment by BlueVsRed12** [comment]
Not a great reason--it's more likely an issue with Crucial 2.

((I took out every mod in the pack minus this one, and the issue remained, so I assumed Abnormals Core was the cause.
However the issue remained even with no mods in the pack, which I assumed wasn't possible until now. hm.))
